### ISSUE TITLE
 More/Dynamic Pages for Widerruf

### ISSUE THREAD

**Issue by GeBon22** [GeBon22/Capstone-Project#10]
### Value Proposition

As a user, I would like to have the feeling of progress within the app --> following directions and jumping onto the requested page. 

### Description

![grafik](https://user-images.githubusercontent.com/114496506/204771981-f0d66ed1-13cd-4fbf-a4d1-30358cf0679f.png)

### Acceptance Criteria

- [ ] there should be several pages 'navigatable' concerning the widerruf theme
- [ ] on the 'widerruf und retoure' page should be a button-style menu leading to the respective pages/content
- [ ] on the nested pages should be a 'zurück' button

### Tasks

(for developers team)

- [x] invent more/dynamic pages
- [x] add the default layout to the new pages
- [x] add the button-style question components and link them to the respective page/content
- [x] add a zurück button, linking to the previous page
- [x] insert the necessary content information (eg. text or 'muster'-content)
- [x] clean up code and let prettier do its magic

### Sizing/Complexity

L
