### ISSUE TITLE
More/Dynamic Pages Online Bestellung

### ISSUE THREAD

**Issue by GeBon22** [GeBon22/Capstone-Project#11]
### Value Proposition
As a user, I would like to have the feeling of progress within the app --> following directions and jumping onto the requested page.

### Description

![grafik](https://user-images.githubusercontent.com/114496506/204775644-5af24d40-4f68-4287-91b8-3ad505dae8be.png)

### Acceptance Criteria

- [ ] there should be several pages 'navigatable' concerning the Online Bestellung theme
- [ ] on the 'widerruf und retoure' page should be a button-style menu leading to the respective pages/content
- [ ] on the nested pages should be a 'zurück' button

### Tasks

(for developers team)

- [x] invent more/dynamic pages
- [x] add the default layout to the new pages
- [x] add the button-style question components and link them to the respective page/content
- [x] add a zurück button, linking to the previous page
- [x] insert the necessary content information (eg. text or 'muster'-content)
- [x] clean up code and let prettier do its magic

### Sizing/Complexity

L
