### ISSUE TITLE
Widerruf Muster Page and additional functions

### ISSUE THREAD

**Issue by GeBon22** [GeBon22/Capstone-Project#13]
### Value Proposition

As a user I would like to be able to use the widerruf content as fully as necessary to get to the validated information. I would like to use the breadcrumb menu, the 'copy' button to copy the muster-texts regarding the widerruf. 

### Description

![grafik](https://user-images.githubusercontent.com/114496506/205079756-ef2f2ad2-373c-4610-b159-2c0971166629.png)

### Acceptance Criteria

- [ ] there should be a breadcrumb menu, a bookmark icon and the kopieren button
- [ ] the breadcrumb menu should be clickable leading to the respective pages
- [ ] the kopieren button should be copying the "muster" text to the clipboard
- [ ] the bookmark icon should not yet be clickable but fixed in its position on the upper right corner of the content section

### Tasks

(for developers team)

- [x] add the missing links to the breadcrumb menu
- [x] add the kopieren button
- [x] write the necessary function for the button to copy the text to the users clipboard
- [x] add the bookmark icon and fix it to the right spot so it does not collide with the breadcrumb menu
- [x] take care of the styling and let prettier do its magic

### Sizing/Complexity

M
