### ISSUE TITLE
code refactoring

### ISSUE THREAD

**Issue by GeBon22** [GeBon22/Capstone-Project#15]
### Value Proposition

As a Web Dev I would like to have a clean code, reviewed and refactored. This includes the recurring use of components just like buttons, bodies, e.a. 

### Description

Just imagine, what nice clean code looks like. 

### Acceptance Criteria

- [ ] the reused components should be stored as such
- [ ] small differences in styling of those components should be made within the respective page --> as 'small' styled.components

### Tasks

(for developers team)

- [ ] refactor the recurring components - i.e. zurück-button, breadcrumb menu,
- [ ] take a look at prettier warnings or other logs and clear out issues
- [ ] use the clean up function and let prettier run

### Sizing/Complexity

M
