### ISSUE TITLE
Polishing and bookmark Page

### ISSUE THREAD

**Issue by GeBon22** [GeBon22/Capstone-Project#17]
### Value Proposition

As a user I would like to have a polished app - with the valuable information I need and with a bookmark Icon that saves the pages and displays it on the bookmark page.

### Description

![grafik](https://user-images.githubusercontent.com/114496506/206225303-57807abb-ebd3-45ca-b326-c84318e2854e.png)
![grafik](https://user-images.githubusercontent.com/114496506/206225476-e99f0713-65e2-45ad-9e33-f9a3fef4f2cd.png)

### Acceptance Criteria

- [ ] the buttons and icons should be in the right places
- [ ] the info texts given should be up to date and accurate
- [ ] when clicking the bookmark icon the link to the page should be displayed on the bookmark page

### Tasks
- [x] add the missing info texts to the respective pages
- [x] position the sections and buttons so that multiple mobile versions display the expected result
- [x] add functionality to the bookmark icons
- [x] make the bookmark page display the marked pages as links

### Sizing/Complexity

L
