### ISSUE TITLE
Google Maps Integration

### ISSUE THREAD

**Issue by GeBon22** [GeBon22/Capstone-Project#19]
### Value Proposition

As a Author, I would like to provide a useful map that shows the user the very own location as well as the lawyers that practice in the respective field in the area. 

### Description

<img width="378" alt="Bildschirmfoto 2022-12-12 um 11 19 31" src="https://user-images.githubusercontent.com/114496506/207021062-c3b41c69-8505-4f65-b558-54dd9f5d1364.png">

### Acceptance Criteria

- [ ] the user should be able to see the location he/she is at
- [ ] there should be location dots in the area displaying the lawyers 
- [ ] the map should be fully zoomable

### Tasks

- [x] introduce the google map api - following the online instructions given by google - apply for a API Key if necessary
- [x] add the location finding function
- [x] implement the necessary functions to display all lawyers within the same area

### Sizing/Complexity
L

**Comment by stefankorder** [comment]
Hello George,
the last task is not a specific task for this user story, but a general task. Therefore, it does not need to be mentioned explicitly, but should always be carried out.
