### ISSUE TITLE
Page listing Lawyers

### ISSUE THREAD

**Issue by GeBon22** [GeBon22/Capstone-Project#20]
### Value Proposition

As user I would like to be able to use a list of all the displayed lawyers, that popped up onto the google map. 

### Description

<img width="379" alt="Bildschirmfoto 2022-12-12 um 11 24 13" src="https://user-images.githubusercontent.com/114496506/207022161-03a7def7-789d-453d-8b3e-2664f73e8559.png">

### Acceptance Criteria

- [ ] there should be a list page that displays the necessary information on the respective lawyers, their field of work, their ratings (if existing)
- [ ] the list should be scrollable
- [ ] the list items should be clickable - with a pointer-cursor

### Tasks

(for developers team)

- [ ] add a list page containing the different lawyer list items
- [ ] add styling and ratings for the respective items
- [ ] make the items clickable

### Sizing/Complexity

M
