### ISSUE TITLE
Additional Feature: Page Ratings Lawyers

### ISSUE THREAD

**Issue by GeBon22** [GeBon22/Capstone-Project#21]
### Value Proposition
As a User it would be nice to have a rating page for the shown list items (eg. Lawyers) I can choose from. 

### Description
<img width="379" alt="Bildschirmfoto 2022-12-12 um 12 00 19" src="https://user-images.githubusercontent.com/114496506/207029814-2dc8757a-010d-4f4c-9fcc-3e84a6ff41b0.png">

### Acceptance Criteria

- [ ] there should be a rating page containing further information on the respective lawyer and - if existing - the google rating
- [ ] the user should be able to scroll through the different ratings

### Tasks

(for developers team)

- [ ] add a page that shows the ratings of the different lawyers in the chosen area
- [ ] add the show more button
- [ ] make the page scrollable

### Sizing/Complexity

M-L
