### ISSUE TITLE
Issue: Copy Button and Header SVG

### ISSUE THREAD

**Issue by GeBon22** [GeBon22/Capstone-Project#25]
### Value Proposition

As author I would like to present a web app with all the functions working properly. 

### Description

![grafik](https://user-images.githubusercontent.com/114496506/208399187-24f7247e-379b-444a-b58c-1df99396b7c3.png)
![grafik](https://user-images.githubusercontent.com/114496506/208399242-2320dcc8-0b4c-4080-8ff1-706d13530fef.png)

### Acceptance Criteria

- [ ] the copy button should work as intended - if clicked the text should be copied to the clipboard displaying a message as confirmation
- [ ] the header animation should be visible and clickable on any page 

### Tasks

- [x] fix the clipboard function 
- [x] make sure there is a message displayed that pops up, when the button is clicked
- [x] fix the SVG animation bug - when switching between pages it sometimes disappears

### Sizing/Complexity

M

**Comment by ufelgen** [comment]
good and simple US! and a very reasonable value proposition ;) hope you can fix all your issues 🤞
