### ISSUE TITLE
Styling and code refactoring

### ISSUE THREAD

**Issue by GeBon22** [GeBon22/Capstone-Project#29]
### Value Proposition

As a author I would like to present a fully styled and working app - as I would love to use as a user. 

### Acceptance Criteria

- [ ] there should be all main colors returning on the different pages and component to have a coherent user experience
- [ ] the general layout is redone establishing a real 'app' feeling to the user
- [ ] header and navbar are going to be components that feel part of the app rather than 'overlayed' components
- [ ] the bookmark icon should display if a page is marked or not

### Tasks

(for developers team)

- [x] save all the used main colors in general variables and reuse them if needed as such in the respective components
- [x] redesign the pagecontainer layout so the app becomes visually a whole work
- [x] implement the header and navbar design into the general app layout so the components no longer sit afloat 
- [x] implement a function so that the bookmark icon changes color when the page is marked

### Sizing/Complexity

L
