### ISSUE TITLE
Feature/Scroll-Up-Button

### ISSUE THREAD

**Issue by GeBon22** [GeBon22/Capstone-Project#30]
### Value Proposition

As a user I would like to use a scroll up button especially when a lot of text is displayed. 

### Description

![grafik](https://user-images.githubusercontent.com/114496506/209964469-f1d04f24-498f-4966-911d-9393664a75fe.png)

### Acceptance Criteria

- [ ] there should be a button that moves the page back up to the top when clicked
- [ ] the button should be at the right location

### Tasks

(for developers team)

- [ ] add a button component with the scrolling up functionality
- [ ] design and style the button according to the US
- [ ] add the button to all the 'information' pages

### Sizing/Complexity

S
