### ISSUE TITLE
#1 Setup Start Page

### ISSUE THREAD

**Issue by GeBon22** [GeBon22/Capstone-Project#4]
### Value Proposition

As a User I need a landing / start page, wich I recognize and use to navigate through the content.

### Description

![Image](https://user-images.githubusercontent.com/114496506/204237388-77a311eb-3260-459c-9582-0995610ec987.png)

### Acceptance Criteria

- [ ] general layout should fit mobile page sizes
- [ ] layout of header and navbar should comply with general mobile sizing

### Tasks

- [x] code default layout
- [x] code default colour vars
- [x] code main section according to design and color layout
- [x] create Header component
- [x] create Navbar component
- [x] size Header
- [x] size main section
- [x] size Navbar

### Sizing/Complexity

**S**
