### ISSUE TITLE
#2 Code Header and Navbar Component

### ISSUE THREAD

**Issue by GeBon22** [GeBon22/Capstone-Project#5]
### Value Proposition

As a user I need a useful header and navbar component for navigation that fits the general layout and needs.

### Description

![grafik](https://user-images.githubusercontent.com/114496506/204238618-445f2942-77e6-45b6-a33e-88cdd840f65d.png)

![grafik](https://user-images.githubusercontent.com/114496506/204238733-195c3ead-4db3-4659-ae0b-6d8d76a2bd05.png)

### Acceptance Criteria

- [ ] the header should show the App Icon which itself should be clickable linking it to the home page
- [ ] the navigation bar should show three icons (home, bookmark, map) 
- [ ] the navbar icons should be clickable linking them to the respectable pages

### Tasks

(for developers team)

- [x] create and import Router
- [x] create Link for favIcon --> Home
- [x] Layout Header
- [x] create Links for navbar --> home, bookmark Page, map Page
- [x] Layout Navbar
- [x] Router import and definition
- [x] header favicon import
- [x] link favIcon to home Page
- [x] create Bookmark Page
- [x] create Map Page
- [x] icon import for navbar
- [x] links for navbar

### Sizing/Complexity

**M**
