### ISSUE TITLE
#3 Home Page

### ISSUE THREAD

**Issue by GeBon22** [GeBon22/Capstone-Project#6]
### Value Proposition

As a user I need a good structured home page with buttons/Links to the usefull content. 

### Description

![grafik](https://user-images.githubusercontent.com/114496506/204242361-d687fb03-f0f8-4cdf-baa5-7a11aaec1dc4.png)

### Acceptance Criteria

- [ ] user should be able to see the question-headline
- [ ] there should be a visible headline linking the "Widerruf" and "Online bestellen" pages
- [ ] next to those healines should be the svg icons
- [ ] the layout should fit the mobile devices sizes

### Tasks

- [x] add headline
- [x] add "Online bestellen und kaufen" button
- [x] add svg/gif/img file thats part of the button-arrangement --> get it working
- [x] add "Widerruf und Retoure" Button
- [x] add svg/gif/img file thats part of the button-arrangement --> get it working
- [x] styling and layout coding

### Sizing/Complexity

** M  **

**Comment by SirJohn42Walker** [comment]
Looks great!
